name: golangci-lint
on:
  push:
    tags:
      - v*
    branches: [ main ]
    paths:
      - '**.go'
      - .golangci.yml
      - .github/workflows/go-lint.yml
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - .golangci.yml
      - .github/workflows/go-lint.yml

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Build
        run: make build

      - name: Format
        run: make go/fmt && git diff --exit-code

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: v1.45.2
