name: Jsonnet

on:
  push:
    branches: [ main ]
    paths:
      - 'deploy/**'
      - '*.jsonnet'
      - '*.libsonnet'
      - .github/workflows/jsonnet.yml
  pull_request:
    branches: [ main ]
    paths:
      - 'deploy/**'
      - '*.jsonnet'
      - '*.libsonnet'
      - .github/workflows/jsonnet.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          cache: true

      - name: Set up Jsonnet
        run: ./env-jsonnet.sh

      - name: Generate
        run: cd deploy && make --always-make vendor manifests

      - name: Archive generatated manifests
        uses: actions/upload-artifact@v3
        with:
          name: manifests
          path: |
            deploy/manifests
