name: Release (Dry Run)

on:
  push:
    branches: [ main ]
    paths:
      - 'go.mod'
      - 'go.sum'
      - ui/**
      - cmd/**
      - pkg/**
      - gen/**
      - .github/workflows/release-dry-run.yml
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - ui/**
      - cmd/**
      - pkg/**
      - gen/**
      - .github/workflows/release-dry-run.yml

permissions:
  contents: write

jobs:
  goreleaser:
    name: Release (Dry Run)
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Set up environment
        run: |
          ./env.sh

      - name: Validate
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: check

      - name: Set Tag
        run: |
          echo "goreleaser_current_tag=`git describe --match 'v*' --tags`" >> $GITHUB_ENV

      - name: Dry Run
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist --skip-validate --skip-publish
        env:
          GORELEASER_CURRENT_TAG: "${{ env.goreleaser_current_tag }}"
